blueprint:
  name: Regulácia VPD
  description: Udržiava VPD na požadovanej hodnote riadením klímy, zvlhčovača a kúrenia
  domain: automation
  input:
    vpd_sensor:
      name: Senzor VPD
      selector:
        entity:
          domain: sensor
    temp_sensor:
      name: Senzor teploty
      selector:
        entity:
          domain: sensor
    hum_sensor:
      name: Senzor vlhkosti
      selector:
        entity:
          domain: sensor
    klima:
      name: Klimatizácia
      selector:
        entity:
          domain: climate
    topene:
      name: Dedikované kúrenie
      selector:
        entity:
          domain: climate
    zvlhcovac:
      name: Zvlhčovač
      selector:
        entity:
          domain: switch
    target_vpd:
      name: Cieľová hodnota VPD
      default: 0.8
      selector:
        number:
          min: 0.1
          max: 2.0
          step: 0.05
          unit_of_measurement: kPa
    target_temp:
      name: Cieľová teplota
      default: 30
      selector:
        number:
          min: 15
          max: 40
          step: 0.5
          unit_of_measurement: "°C"
    hum_low:
      name: Minimálna vlhkosť (hranica pre zvlhčovanie)
      default: 55
      selector:
        number:
          min: 30
          max: 70
          step: 1
          unit_of_measurement: "%"
    hum_high:
      name: Maximálna vlhkosť (hranica pre sušenie)
      default: 70
      selector:
        number:
          min: 60
          max: 90
          step: 1
          unit_of_measurement: "%"

trigger:
  - platform: state
    entity_id: !input vpd_sensor
  - platform: state
    entity_id: !input temp_sensor
  - platform: state
    entity_id: !input hum_sensor

mode: single

action:
  - variables:
      vpd: "{{ states(vpd_sensor) | float(0) }}"
      temp: "{{ states(temp_sensor) | float(0) }}"
      hum: "{{ states(hum_sensor) | float(0) }}"
      target_vpd: !input target_vpd
      target_temp: !input target_temp
      hum_low: !input hum_low
      hum_high: !input hum_high

  - choose:
      # Sušenie
      - conditions:
          - condition: template
            value_template: "{{ hum > hum_high and vpd < target_vpd }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input klima
            data:
              hvac_mode: dry
          - service: climate.set_hvac_mode
            target:
              entity_id: !input topene
            data:
              hvac_mode: heat
          - service: switch.turn_off
            target:
              entity_id: !input zvlhcovac

      # Zvlhčovanie
      - conditions:
          - condition: template
            value_template: "{{ hum < hum_low and vpd > target_vpd }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input zvlhcovac
          - service: climate.set_hvac_mode
            target:
              entity_id: !input klima
            data:
              hvac_mode: auto
          - service: climate.set_temperature
            target:
              entity_id: !input klima
            data:
              temperature: "{{ target_temp }}"

      # Regulácia teploty (normálna zóna vlhkosti)
      - conditions:
          - condition: template
            value_template: "{{ hum >= hum_low and hum <= hum_high }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input klima
            data:
              hvac_mode: auto
          - service: climate.set_temperature
            target:
              entity_id: !input klima
            data:
              temperature: "{{ target_temp }}"
          - service: switch.turn_off
            target:
              entity_id: !input zvlhcovac
          - service: climate.set_hvac_mode
            target:
              entity_id: !input topene
            data:
              hvac_mode: "off"
