blueprint:
  name: VPD humidifier controller (event-driven)
  description: |
    Listens for `vpd_mode` events from the decider and toggles the humidifier.
    ON in humidify, OFF otherwise.
  domain: automation
  input:
    zvlhcovac:
      name: Zvlhčovač (switch)
      selector:
        entity:
          domain: switch
    enable_switch:
      name: Prepínač povolenia regulácie
      selector:
        entity:
          domain: input_boolean

    # Notifikácie (voliteľné)
    notify_enable_phone:
      name: Posielať notifikácie na telefón?
      default: true
      selector:
        boolean:
    notify_device:
      name: Telefón pre notifikácie
      default: []
      selector:
        device:
          integration: mobile_app
    notify_enable_ui:
      name: Posielať notifikácie do HA UI?
      default: false
      selector:
        boolean:

trigger:
  - platform: event
    event_type: vpd_mode

mode: restart

condition:
  - condition: state
    entity_id: !input enable_switch
    state: "on"

action:
  - variables:
      mode: "{{ trigger.event.data.mode | default('normal') }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ mode == 'humidify' }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input zvlhcovac
          # Notifikácie
          - choose:
              - conditions: "{{ notify_enable_phone }}"
                sequence:
                  - domain: mobile_app
                    type: notify
                    device_id: !input notify_device
                    title: "VPD Humidifier: ON"
                    message: "Humidifier turned ON (mode=humidify)"
              - conditions: "{{ notify_enable_ui }}"
                sequence:
                  - service: persistent_notification.create
                    data:
                      title: "VPD Humidifier: ON"
                      message: "Humidifier turned ON (mode=humidify)"
    default:
      - service: switch.turn_off
        target:
          entity_id: !input zvlhcovac
      - choose:
          - conditions: "{{ notify_enable_phone }}"
            sequence:
              - domain: mobile_app
                type: notify
                device_id: !input notify_device
                title: "VPD Humidifier: OFF"
                message: "Humidifier turned OFF (mode!=humidify)"
          - conditions: "{{ notify_enable_ui }}"
            sequence:
              - service: persistent_notification.create
                data:
                  title: "VPD Humidifier: OFF"
                  message: "Humidifier turned OFF (mode!=humidify)"


